server:
  port: 9026

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db
    username: root
    password: (2#5ZqnT8x
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

